### ISSUE TITLE
JDBC Meta data

### ISSUE THREAD

**Issue by ryanhamilton** [taosdata/taos-connector-jdbc#111]
```

			PoolableConnection conn = getConnection(serverConfig);
			DatabaseMetaData md = conn.getMetaData();
			//  TABLE_CAT:`; TABLE_SCHEM:`; TABLE_NAME:`
			String db = serverConfig.getDatabase();
			ResultSet rs = md.getTables(db, null, "%", new String[] {"TABLE","VIEW"});
```

``md.getTables("db", null, "%", new String[] {"TABLE","VIEW"});`` - returns the tables "db" only, with the TABLE_CAT populated
``md.getTables(null, null, "%", new String[] {"TABLE","VIEW"});``  - returns all tables but does NOT populate TABLE_CAT 

Is there a way to fetch all tables in all schemas AND populate the TABLE_CAT column?
Closely related test: https://github.com/taosdata/taos-connector-jdbc/blob/ba7fe522eecdcdcf23738b01faefca12cf837daa/src/test/java/com/taosdata/jdbc/rs/RestfulDatabaseMetaDataTest.java#L632-L635

Also your information_schema tables are prefixed INS_XXXXXX, is there a reason for that?
https://docs.tdengine.com/taos-sql/meta/#ins_columns

**Comment by ryanhamilton** [comment]
As background, I am trying to get TDEngine working well in qStudio.
qStudio is a free tool for data analysts to run SQL queries and view tabular results and charts.
https://www.timestored.com/qstudio/

I want the generic JDBC calls to work similar to other databases, so that the server tree view etc. work.

![image](https://github.com/taosdata/taos-connector-jdbc/assets/7273208/d036898d-ccbf-441f-8cde-5a6a9b6d5d46)

**Comment by sangshuduo** [comment]
@ryanhamilton  Thank you for your effort to make TDengine work with qStudio. 

Regarding the issue `md.getTables(null, null, "%", new String[] {"TABLE","VIEW"});` - returns all tables but does NOT populate TABLE\_CAT, we will fix it in next release.

The information\_schema column name is just to make them easy to be discriminated against ordinary table columns. No more reason.

BTW, may I know if you have read the official document of TDengine? Especially the concept section, [https://docs.tdengine.com/concept/](https://docs.tdengine.com/concept/). TDengine uses super table as the template to make sub table has the same schema. I suggest qStudio support it as a unique feature of TDengine.

**Comment by ryanhamilton** [comment]
I had seen the concept but hadn't really thought out how it would affect the UI.
I guess the question is, **what do your users want from a UI?**

**Comment by sangshuduo** [comment]
> I had seen the concept but hadn't really thought out how it would affect the UI. I guess the question is, **what do your users want from a UI?**

Users should be aware of their existence and some sub-tables belonging to one of them. As what I imagine. :)

**Comment by sangshuduo** [comment]
@ryanhamilton Hello, I installed the latest qStudio and am happy to see it already supports TDengine. When I click each table under the database I connected, I can see there is a 'unknownColumns' sub-item under the table. May I know if you will resolve it soon? Thanks.

**Comment by ryanhamilton** [comment]
> @ryanhamilton Hello, I installed the latest qStudio and am happy to see it already supports TDengine. When I click each table under the database I connected, I can see there is a 'unknownColumns' sub-item under the table. May I know if you will resolve it soon? Thanks.

Hi @sangshuduo 

I'm not sure how to retrieve the columns without knowing the database name in advance.
Most other databases you call ``getColumns(null, "%", "%", "%")`` or ``getColumns(null,null,null,null)`` 
and they return all tables in all databases in all schemas. TDengine doesn't seem to do this?

As far as I can tell you don't support null as a first argument at all. Your tests only show the database name being supplied.

Is there one call that will return all column names in all databases and schemas?

**Comment by sangshuduo** [comment]
@ryanhamilton  thanks for your finding, we will support getColumns(null) in our JDBC connector to return all columns.
CC @huolibo

**Comment by huolibo** [comment]
hi @ryanhamilton, i have fixed the problem. [#113 ](https://github.com/taosdata/taos-connector-jdbc/pull/113).

**Comment by sangshuduo** [comment]
> hi @ryanhamilton, i have fixed the problem. [#113](https://github.com/taosdata/taos-connector-jdbc/pull/113) .

Could you please verify if it solves the problem? It will be included in the next release.

**Comment by sheyanjie-qq** [comment]
close this issue for no further information
