### ISSUE TITLE
移除fastjson后JNI启动报错

### ISSUE THREAD

**Issue by melvin7** [taosdata/taos-connector-jdbc#112]
使用JNI模式，无法排除fastjson依赖
`<dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>3.2.4</version>
            <exclusions>
                <exclusion>
                    <artifactId>fastjson</artifactId>
                    <groupId>com.alibaba</groupId>
                </exclusion>
            </exclusions>
        </dependency>
`
原因在于 TSDBJNIConnector 中引用了fastjson
`JSONObject configJSON = new JSONObject();
for (String key : props.stringPropertyNames()) {
    configJSON.put(key, props.getProperty(key));
}
setConfigImp(configJSON.toJSONString());
`

JNI中就这么一小段试用了fastjson，完全没有必要

**Comment by itzlyg** [comment]
看见fastjson慌，搜了下，里面用的还蛮多，在想怎么解决。

**Comment by sheyanjie-qq** [comment]
3.4.0 已经使用 Jackson
