### ISSUE TITLE
Bug: TSDBDatabaseMetaData get metadata return "invalid system table name"

### ISSUE THREAD

**Issue by enix223** [taosdata/taos-connector-jdbc#153]
# Environment:

* server version: tdengine-3.1.0.3
* jdbc version: 3.2.8
* jdk version: JDK 17

# Reproduce:

```java
  private boolean isTableExist(Connection connection, String tableName) throws SQLException {
    var dbname = connection.getCatalog();
    var metadata = connection.getMetaData().unwrap(TSDBDatabaseMetaData.class);
    try (var ignore = metadata.getColumns(dbname, "", tableName, "")) {
      return true;
    } catch (SQLException e) {
      return false;
    }
  }
```

When running with the above code, exception is raised: `TDengine ERROR (0x80002662): Fail to get table info, error: Invalid system table name`.

This issue was introduced with the latest jdbc connector, and the same piece of codes run ok with `3.2.4` version.

Would you please help to investigate?

**Comment by sheyanjie-qq** [comment]
3.2.8 only support  TDengine 3.2.0.0+
