### ISSUE TITLE
WSClient核心线程数

### ISSUE THREAD

**Issue by macbookpro2016** [taosdata/taos-connector-jdbc#158]
WSClient核心线程数为什么是1，单线程池的作用是什么，调用很容易出错

**Comment by macbookpro2016** [comment]
在taos提供的kafka-connector中，sink的时候调用cacheProcessor#schemalesswirite，每次都会创建线程池并没有关闭，导致线程数逐渐增大到系统限制
<img width="1174" alt="image" src="https://github.com/taosdata/taos-connector-jdbc/assets/24033636/2d5e0362-3da2-483f-a377-8bc16fcf6c04">

**Comment by macbookpro2016** [comment]
> 请仔细描述您遇到的问题，什么情况下会出错？

在taos提供的kafka-connector中，sink的时候调用cacheProcessor#schemalesswirite，每次都会创建线程池并没有关闭，导致线程数逐渐增大到系统限制

**Comment by macbookpro2016** [comment]
![image](https://github.com/taosdata/taos-connector-jdbc/assets/24033636/8d119457-64d5-44f9-90fe-fcb5b910cb63)

**Comment by sheyanjie-qq** [comment]
@macbookpro2016  这是 kafaka Connector 的问题，我们这周会修复一下

**Comment by sheyanjie-qq** [comment]
最新版本已经 fix，升级了 jdbc 驱动，然后直接用连接方法即可。
