### ISSUE TITLE
wasnull方法返回值异常

### ISSUE THREAD

**Issue by homeless2010** [taosdata/taos-connector-jdbc#42]
![335321201476dd4d63df46d27972f26](https://user-images.githubusercontent.com/26829140/185587693-b7a50eb4-eda4-4290-a723-dfb90b247eec.jpg)
!= null是不是要置为 false
![896917f22dee7a7932984b6fdc3a189](https://user-images.githubusercontent.com/26829140/185587784-684688a8-478c-4744-b823-bec4825e8b38.jpg)
使用springjdbctemplate
![8d05250508bc20e3b927e14cf0f6d8b](https://user-images.githubusercontent.com/26829140/185587903-ca13f7c7-0567-47b7-b591-76c2d9d6d9de.jpg)
发现wasnull返回true而实际有值 导致查询错误

**Comment by huolibo** [comment]
已提交更改。https://github.com/taosdata/taos-connector-jdbc/pull/43。感谢反馈
