### ISSUE TITLE
3.0版本与ibatis使用int=0和boolean=false对象赋值为null

### ISSUE THREAD

**Issue by liangleiA** [taosdata/taos-connector-jdbc#51]
版本3.0 当和mybatis plus一起使用时， 该日志注解会导致 int是0和boolean是false类型的参数都被赋值为null，去掉日志打印注解则不会出现。
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
调试时发现，加上日志注解会导致TSDBResultSetBlockData get方法提前赋值wasNull = true。 导致ibatis对象赋值时判断出现问题
![image](https://user-images.githubusercontent.com/22088365/201816388-6498677d-1e0f-4a26-822b-8f097b71beb7.png)

**Comment by liangleiA** [comment]
目前解决办法， 要吗不打印日志， 要吗 配置 关掉 batchfetch=false

**Comment by huolibo** [comment]
使用哪个 taos-jdbc 版本呢？

**Comment by liangleiA** [comment]
>jdbc 3.0.0版本

**Comment by huolibo** [comment]
请升级到 3.0.2 版本。
