### ISSUE TITLE
版本3.0.0及以上 windows环境中使用last 函数配合别名在mybatis中无法映射

### ISSUE THREAD

**Issue by liangleiA** [taosdata/taos-connector-jdbc#53]
windows系统 在mybatis环境中使用jdbc3.0.2驱动，使用查询sql方法如下， select last(ts) as real_time , last(v) as value_collect  from test 映射到对象上的realTime和valueCollect。 预期realTime和valueCollect正常映射到数据。但是结果确是null,增加ts和v参数， 发现数据还是映射在ts和v参数上。 该问题在linux系统中是正常的。于是调试发现
![image](https://user-images.githubusercontent.com/22088365/203070383-d57a11e3-7e8e-49cb-8644-c1fc177d0e38.png)
unMappedColumnNames在linux和windows中运行的结果并不一样。 linux是正确的，所以未出问题。而windows并没有用别名映射对象。而仍然使用的ts和v进行对象赋值。

**Comment by huolibo** [comment]
尝试在 windows 环境 taos shell 中执行以上 SQL。查看别名方式是否可以正常执行。

**Comment by liangleiA** [comment]
> 尝试在 windows 环境 taos shell 中执行以上 SQL。查看别名方式是否可以正常执行。

windows shell环境是可以查询出别名的， 但是跟mybatis使用则不行。希望你们可以复现一下，以确认问题。

**Comment by huolibo** [comment]
创建连接的 url 是什么？

**Comment by liangleiA** [comment]
jdbc:TAOS://192.168.3.104:6030/iot_data?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8

**Comment by liangleiA** [comment]
> 创建连接的 url 是什么？

  driver: com.taosdata.jdbc.TSDBDriver
  url: jdbc:TAOS://192.168.3.104:6030/iot_data?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
  username: root
  password: taosdata

**Comment by liangleiA** [comment]
复现：
![image](https://user-images.githubusercontent.com/22088365/204170724-f7a99512-0a2a-4e09-b983-269413dc3d34.png)
正常使用as 映射到 realTime和valueCollectTest
配合last使用as 无法映射到realTime和valueCollectTest, 映射到了ts和value_collect
![image](https://user-images.githubusercontent.com/22088365/204170852-6159f853-4579-4916-8f7f-deaf1f95245f.png)

**Comment by huolibo** [comment]
能否将此测试程序打一个压缩包，我本地复现一下。

**Comment by liangleiA** [comment]
> 



> 能否将此测试程序打一个压缩包，我本地复现一下。

你们没有复现吗？我压缩包不好上传

**Comment by liangleiA** [comment]
> 能否将此测试程序打一个压缩包，我本地复现一下。

我卸载干净tdengine，重新安装新的，问题神奇没有了...
