### ISSUE TITLE
参数绑定写入报错

### ISSUE THREAD

**Issue by lliaozhijin** [taosdata/taos-connector-jdbc#54]
tdengine使用3.0.1.6，使用文档上的参数绑定写入数据，但是报这个错误
![31669024943_ pic](https://user-images.githubusercontent.com/44841530/203109539-4d228e3c-ccf9-436e-91c8-8cbf6b287cf1.jpg)

**Comment by sangshuduo** [comment]
请确定一下是否系统中是否有老版本的 taosd 在运行 和 taos client 版本不匹配？

**Comment by sheyanjie-qq** [comment]
close this issue for no further infomation.
