### ISSUE TITLE
windows环境tdengine3,mybatis中   last_row(*) 无法映射数据到实体

### ISSUE THREAD

**Issue by liangleiA** [taosdata/taos-connector-jdbc#55]
windows mybatis环境下  last_row(*) 无法映射到数据库实体的参数上，而部署到linux环境却没有问题，能正常映射到实体。
1. xml 查询sql如下：
![image](https://user-images.githubusercontent.com/22088365/204694788-5487e07b-146e-422a-8234-3e2c2511adcd.png)
2. linux环境调试结果 
![image](https://user-images.githubusercontent.com/22088365/204694920-261a326a-44fa-48f5-bbf0-63d18a2f5669.png)
3. windows环境调试结果
![image](https://user-images.githubusercontent.com/22088365/204695412-3097f0a3-31dd-4684-85e6-0ab8b6430649.png)

**Comment by liangleiA** [comment]
jdbc 版本3.0.0 ， 3.0.2。  tdengine服务端 linux taos 3.0.1.6  有问题客户端 windows java jdbc ，连接方式： 原生。 连接jdbc:TAOS://192.168.3.104:6030/iot_data?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8

**Comment by huolibo** [comment]
请升级 jdbc 版本到 3.0.2

**Comment by huolibo** [comment]
请参考： [配置参数](https://docs.taosdata.com/reference/config/#keepcolumnname)

**Comment by liangleiA** [comment]
1.windows环境配置 url jdbc:TAOS://xxxxxxxx/iot_data?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8&cfgdir=taos.cfg
2.项目下添加taos.cfg 增加配置  keepColumnName		1
3. 映射问题解决。
