### ISSUE TITLE
发行版Releases中能不能添加打包好的jar?总共3个jar文件。

### ISSUE THREAD

**Issue by 15678871232** [taosdata/taos-connector-jdbc#85]
发行版Releases中能不能添加打包好的jar?总共3个，今天下载依赖并打包浪费了半天时间。
taos-jdbcdriver-3.1.0.jar
taos-jdbcdriver-3.1.0-dist.jar
taos-jdbcdriver-3.1.0-sources.jar

**Comment by u5de6** [comment]
+1

**Comment by sheyanjie-qq** [comment]
这些 jar 会导致发行版安装包变大，不是所有用户都需要
